#!/usr/bin/env node
/**
 * Writes public/sw.js with cache name tied to package.json version.
 * Run from prebuild:web and after expo export (dist/sw.js).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const version = pkg.version ?? '0.0.0';
const cacheId = version.replace(/[^a-zA-Z0-9.-]/g, '-');

const swSource = `/* Stickera PWA — generated by scripts/write-sw.mjs (v${version}) */
const CACHE = 'stickera-${cacheId}';
const BASE = '/stickera/';

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (!url.pathname.startsWith(BASE)) return;

  const isAppShell =
    url.pathname.endsWith('.html') ||
    url.pathname.includes('/_expo/') ||
    url.pathname.endsWith('.js') ||
    url.pathname.endsWith('.css');

  if (!isAppShell && !url.pathname.includes('catalog.json') && !url.pathname.includes('/albums/')) {
    return;
  }

  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const cached = await cache.match(event.request);
      try {
        const res = await fetch(event.request);
        if (res.ok) cache.put(event.request, res.clone());
        return res;
      } catch {
        if (cached) return cached;
        throw new Error('offline');
      }
    }),
  );
});
`;

function writeSw(targetPath) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, swSource);
}

const dest = process.argv[2];
if (dest) {
  writeSw(path.resolve(ROOT, dest));
  console.log(`✅ sw.js → ${path.relative(ROOT, path.resolve(ROOT, dest))} (cache: stickera-${cacheId})`);
} else {
  writeSw(path.join(ROOT, 'public', 'sw.js'));
  console.log(`✅ sw.js → public/sw.js (cache: stickera-${cacheId})`);
}
